-- ./settings/simpleui/sui_settings.lua
return {
    ["simpleui_bar_enabled"] = true,
    ["simpleui_bar_mode"] = "both",
    ["simpleui_bar_tabs"] = {
        [1] = "home",
        [2] = "sui_settings",
        [3] = "homescreen",
        [4] = "history",
        [5] = "power",
    },
    ["simpleui_browsemeta_enabled"] = true,
    ["simpleui_enabled"] = true,
    ["simpleui_fc_cover_mode"] = "2_3",
    ["simpleui_fc_enabled"] = true,
    ["simpleui_fc_folder_style"] = "auto",
    ["simpleui_fc_subfolder_cover"] = true,
    ["simpleui_hide_label_clock"] = false,
    ["simpleui_hide_label_coverdeck"] = false,
    ["simpleui_hide_label_currently"] = false,
    ["simpleui_hide_label_recent"] = false,
    ["simpleui_hs_action_list_enabled"] = false,
    ["simpleui_hs_active_preset"] = "builtin_library_view",
    ["simpleui_hs_clock_battery"] = true,
    ["simpleui_hs_clock_date"] = true,
    ["simpleui_hs_clock_date_gap"] = 80,
    ["simpleui_hs_clock_enabled"] = true,
    ["simpleui_hs_clock_scale"] = 100,
    ["simpleui_hs_collections_enabled"] = false,
    ["simpleui_hs_coverdeck_enabled"] = true,
    ["simpleui_hs_coverdeck_gap_pct"] = 50,
    ["simpleui_hs_coverdeck_item_label_scale"] = 100,
    ["simpleui_hs_coverdeck_main_order"] = {
        [1] = "covers",
        [2] = "title",
        [3] = "author",
        [4] = "progress",
        [5] = "stats",
    },
    ["simpleui_hs_coverdeck_scale"] = 100,
    ["simpleui_hs_coverdeck_show_author"] = false,
    ["simpleui_hs_coverdeck_show_book_days"] = false,
    ["simpleui_hs_coverdeck_show_book_remaining"] = false,
    ["simpleui_hs_coverdeck_show_book_time"] = false,
    ["simpleui_hs_coverdeck_show_percent"] = false,
    ["simpleui_hs_coverdeck_show_progress"] = false,
    ["simpleui_hs_coverdeck_show_title"] = true,
    ["simpleui_hs_coverdeck_source"] = "recent",
    ["simpleui_hs_coverdeck_stats_order"] = {},
    ["simpleui_hs_coverdeck_thumb_scale"] = 80,
    ["simpleui_hs_coverdeck_title_pos"] = "below",
    ["simpleui_hs_currently_bar_style"] = "with_pct",
    ["simpleui_hs_currently_cover_gap"] = 120,
    ["simpleui_hs_currently_elem_order"] = {
        [1] = "title",
        [2] = "author",
        [3] = "progress",
        [4] = "percent",
    },
    ["simpleui_hs_currently_enabled"] = false,
    ["simpleui_hs_currently_item_label_scale"] = 100,
    ["simpleui_hs_currently_scale"] = 80,
    ["simpleui_hs_currently_show_author"] = true,
    ["simpleui_hs_currently_show_book_days"] = false,
    ["simpleui_hs_currently_show_book_remaining"] = false,
    ["simpleui_hs_currently_show_book_time"] = false,
    ["simpleui_hs_currently_show_frame"] = true,
    ["simpleui_hs_currently_show_percent"] = true,
    ["simpleui_hs_currently_show_progress"] = true,
    ["simpleui_hs_currently_show_title"] = true,
    ["simpleui_hs_currently_solid_bg"] = false,
    ["simpleui_hs_currently_stats_style"] = "compact",
    ["simpleui_hs_currently_thumb_scale"] = 90,
    ["simpleui_hs_hero_currently"] = false,
    ["simpleui_hs_hero_currently_cover_scale"] = 110,
    ["simpleui_hs_hero_currently_desc_fs_scale"] = 110,
    ["simpleui_hs_module_order"] = {
        [1] = "clock",
        [2] = "coverdeck",
        [3] = "new_books",
        [4] = "quote",
        [5] = "currently",
        [6] = "recent",
        [7] = "tbr",
        [8] = "collections",
        [9] = "reading_goals",
        [10] = "reading_stats",
        [11] = "action_list",
        [12] = "hero_currently",
        [13] = "reading_insights",
        [14] = "reading_streaks",
        [15] = "recent_book_stats",
    },
    ["simpleui_hs_new_books_enabled"] = true,
    ["simpleui_hs_quote_enabled"] = false,
    ["simpleui_hs_reading_goals_enabled"] = false,
    ["simpleui_hs_reading_insights"] = false,
    ["simpleui_hs_reading_stats_enabled"] = false,
    ["simpleui_hs_reading_streaks"] = false,
    ["simpleui_hs_recent_book_stats"] = false,
    ["simpleui_hs_recent_enabled"] = false,
    ["simpleui_hs_recent_item_label_scale"] = 90,
    ["simpleui_hs_recent_scale"] = 100,
    ["simpleui_hs_recent_show_finished"] = false,
    ["simpleui_hs_recent_show_frame"] = false,
    ["simpleui_hs_recent_show_overlay"] = false,
    ["simpleui_hs_recent_show_progress"] = false,
    ["simpleui_hs_recent_show_text"] = true,
    ["simpleui_hs_recent_solid_bg"] = false,
    ["simpleui_hs_recent_thumb_scale"] = 80,
    ["simpleui_hs_return_on_wakeup"] = false,
    ["simpleui_hs_tbr_enabled"] = false,
    ["simpleui_layout"] = {
        ["pages"] = {
            [1] = {
                ["id"] = 1,
                ["modules"] = {
                    [1] = "clock",
                    [2] = "coverdeck",
                    [3] = "new_books",
                },
            },
        },
    },
    ["simpleui_loaded_version"] = "2.1.1",
    ["simpleui_navbar_transparent"] = false,
    ["simpleui_onboarding_done"] = true,
    ["simpleui_preserve_deleted_books_in_stats"] = false,
    ["simpleui_qa_list"] = {},
    ["simpleui_qa_migrated_v1"] = true,
    ["simpleui_qa_row_instances"] = {},
    ["simpleui_qs_bar_bg"] = "flat",
    ["simpleui_qs_bar_enabled"] = true,
    ["simpleui_qs_bar_frontlight"] = false,
    ["simpleui_qs_bar_settings_on_hold"] = true,
    ["simpleui_qs_bar_shape"] = "round",
    ["simpleui_qs_bar_slots"] = {
        [1] = "wifi_toggle",
        [2] = "bookmark_browser",
        [3] = "frontlight",
        [4] = "night_mode",
        [5] = "power",
        [6] = "sui_settings",
    },
    ["simpleui_qs_bar_warmth"] = false,
    ["simpleui_quote_deck_count"] = 99,
    ["simpleui_quote_deck_order"] = "66,53,77,40,86,27,99,59,49,24,44,8,20,33,78,58,47,31,30,39,14,6,36,37,38,26,57,12,25,19,13,56,96,71,5,68,63,95,55,76,2,29,46,61,81,50,23,64,65,43,21,88,72,93,54,45,73,41,4,15,75,51,91,98,79,87,62,90,17,16,84,85,80,32,18,7,74,94,52,60,48,11,89,34,92,67,1,3,69,83,22,97,82,28,70,10,42,9,35",
    ["simpleui_quote_deck_pos"] = 3,
    ["simpleui_reading_goals_show_annual"] = true,
    ["simpleui_reading_goals_show_daily"] = false,
    ["simpleui_reading_goals_show_monthly"] = false,
    ["simpleui_settings_migrated_v2"] = true,
    ["simpleui_settings_migrated_v3"] = true,
    ["simpleui_settings_migrated_v4"] = true,
    ["simpleui_settings_migrated_v5"] = true,
    ["simpleui_settings_migrated_v6"] = true,
    ["simpleui_settings_migrated_v7"] = true,
    ["simpleui_settings_migrated_v8"] = true,
    ["simpleui_stale_books_v1"] = {
        ["prefetched_data"] = {
            ["/mnt/us/epubs/AI Product Manager's Handbook - B22451_12 (for Duc Pham) - Second Edition IRENE BRATSIS -- 2024 (238).epub"] = {
                ["authors"] = "Second Edition IRENE BRATSIS -- 2024",
                ["doc_pages"] = 670,
                ["partial_md5_checksum"] = "9ba83ef0ca02ba81f142b9114e7fb27d",
                ["percent"] = 0.48507462686567,
                ["stat_pages"] = 600,
                ["summary"] = {
                    ["modified"] = "2026-04-19",
                    ["status"] = "reading",
                },
                ["title"] = "AI Product Manager's Handbook - B22451_12 (for Duc Pham)",
            },
            ["/mnt/us/epubs/AI Product Playbook_ Strategies, Skills, and Frameworks for the Product Manager, The - Marily Nika & Diego Granados (112).epub"] = {
                ["authors"] = "Marily Nika\
Diego Granados",
                ["doc_pages"] = 453,
                ["partial_md5_checksum"] = "a956e85274cdf567d234715afe64a8d5",
                ["percent"] = 0.0088300220750552,
                ["stat_pages"] = 453,
                ["summary"] = {
                    ["modified"] = "2026-04-19",
                    ["status"] = "reading",
                },
                ["title"] = "The AI Product Playbook: Strategies, Skills, and Frameworks for the AI-Driven Product Manager",
            },
            ["/mnt/us/epubs/New Revised Standard Version Updated Bible _ With Deuterocanonithe Old Testament - National Council of Churches USA (342).epub"] = {
                ["authors"] = "National Council of Churches USA",
                ["doc_pages"] = 7380,
                ["partial_md5_checksum"] = "b5b6098b28a8234f84a54a78db9590f8",
                ["percent"] = 0.81815718157182,
                ["stat_pages"] = 7380,
                ["summary"] = {
                    ["modified"] = "2026-01-01",
                    ["status"] = "reading",
                },
                ["title"] = "New Revised Standard Version Updated Bible : With Deuterocanonical and Apocryphal Books of the Old Testament",
            },
            ["/mnt/us/epubs/Vibe Coding Building Production-Grade Software With GenAI, Chat, Agents, and Beyond (Gene Kim, Steve Yegge) (z-library.sk, 1lib.sk, z-lib.sk).epub"] = {
                ["authors"] = "Gene Kim\
Steve Yegge",
                ["doc_pages"] = 550,
                ["partial_md5_checksum"] = "f3589a39ad62ca0e29ddb992cb0bcf49",
                ["percent"] = 0.31454545454545,
                ["summary"] = {
                    ["modified"] = "2026-07-18",
                    ["status"] = "reading",
                },
                ["title"] = "Vibe Coding",
            },
            ["/mnt/us/koreader/cache/appstore/readme/AlgusDark_karakeep_koplugin_README.md"] = {
                ["doc_pages"] = 3,
                ["partial_md5_checksum"] = "44fbfd294cf0bee72bdf4a1c73b4357b",
                ["percent"] = 0.33333333333333,
                ["stat_pages"] = 3,
                ["summary"] = {
                    ["modified"] = "2025-11-24",
                    ["status"] = "reading",
                },
                ["title"] = "AlgusDark_karakeep_koplugin_README",
            },
            ["/mnt/us/koreader/cache/appstore/readme/IntrovertedMage_AO3Downloader_koplugin_README.md"] = {
                ["doc_pages"] = 2,
                ["partial_md5_checksum"] = "0c9986b9da0578de6e45012dc3458111",
                ["percent"] = 0.5,
                ["stat_pages"] = 2,
                ["summary"] = {
                    ["modified"] = "2025-11-24",
                    ["status"] = "reading",
                },
                ["title"] = "IntrovertedMage_AO3Downloader_koplugin_README",
            },
            ["/mnt/us/koreader/help/quickstart-en-v2025.04.html"] = {
                ["doc_pages"] = 8,
                ["partial_md5_checksum"] = "f57f1d89ea1f37a9c43b68371cb7899d",
                ["percent"] = 1,
                ["stat_pages"] = 8,
                ["summary"] = {
                    ["modified"] = "2025-10-10",
                    ["status"] = "complete",
                },
                ["title"] = "KOReader Quickstart Guide",
            },
        },
        ["recent_fps"] = {
            [1] = "/mnt/us/epubs/Vibe Coding Building Production-Grade Software With GenAI, Chat, Agents, and Beyond (Gene Kim, Steve Yegge) (z-library.sk, 1lib.sk, z-lib.sk).epub",
            [2] = "/mnt/us/epubs/AI Product Manager's Handbook - B22451_12 (for Duc Pham) - Second Edition IRENE BRATSIS -- 2024 (238).epub",
            [3] = "/mnt/us/epubs/AI Product Playbook_ Strategies, Skills, and Frameworks for the Product Manager, The - Marily Nika & Diego Granados (112).epub",
            [4] = "/mnt/us/epubs/New Revised Standard Version Updated Bible _ With Deuterocanonithe Old Testament - National Council of Churches USA (342).epub",
            [5] = "/mnt/us/koreader/cache/appstore/readme/AlgusDark_karakeep_koplugin_README.md",
            [6] = "/mnt/us/koreader/cache/appstore/readme/IntrovertedMage_AO3Downloader_koplugin_README.md",
            [7] = "/mnt/us/koreader/help/quickstart-en-v2025.04.html",
        },
    },
    ["simpleui_statusbar_transparent"] = false,
    ["simpleui_streak_freeze_last_total_secs"] = 5809,
    ["simpleui_streak_freeze_watermark"] = 0,
    ["simpleui_style_wallpaper_enabled"] = false,
    ["simpleui_tb_fm_cfg"] = {
        ["order_left"] = {
            [1] = "fm_back",
            [2] = "fm_search",
        },
        ["order_right"] = {
            [1] = "fm_browse",
            [2] = "fm_menu",
        },
        ["side"] = {
            ["fm_back"] = "left",
            ["fm_browse"] = "right",
            ["fm_menu"] = "right",
            ["fm_search"] = "left",
        },
    },
    ["simpleui_tb_item_fm_browse"] = true,
    ["simpleui_tb_item_fm_search"] = true,
    ["simpleui_topbar_config"] = {
        ["order_left"] = {
            [1] = "clock",
        },
        ["order_right"] = {
            [1] = "wifi",
            [2] = "battery",
        },
        ["side"] = {
            ["battery"] = "right",
            ["clock"] = "left",
            ["wifi"] = "right",
        },
    },
    ["simpleui_topbar_enabled"] = true,
    ["simpleui_updater_auto_check"] = true,
    ["simpleui_wallpaper_show_in_fm"] = false,
}
